---
# The list of servers.
servers:
  -
    name: gazebo
    url: https://fuel.gazebosim.org

  -
    name: ignition
    url: https://fuel.ignition.org

# Where are the assets stored in disk.
# cache:
#   path: /tmp/ignition/fuel
